name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          # you have create a NPM account, generate
          # a NPM_TOKEN and then add the token to the
          # repo's SECRETS so this action can use the token
          # and publish the package for you, on NPM
          token: ${{ secrets.NPM_TOKEN }}
